export interface DefaultModule {
  name: string;
  shortDesc: string;
  description: string;
  pricingModel: 'fixed' | 'monthly' | 'hourly';
  price: number;
  serviceType: 'core' | 'addon';
  deliverables: string[];
  clientResponsibilities: string[];
  outOfScope: string[];
  defaultTimeline: string;
  suggestedKpis: string[];
  commonTools: string[];
  aiContext?: string;
}

export const defaultModulesByGroup: Record<string, DefaultModule[]> = {
  'Brand & Creative': [
    {
      name: 'Brand Identity System',
      shortDesc: 'Logo, typography, color palette, and brand guidelines',
      description: 'Complete visual identity development or refresh including logo design, color system, typography, and comprehensive brand guidelines document. Designed to give the client a cohesive, professional brand that works across all touchpoints.',
      pricingModel: 'fixed',
      price: 8500,
      serviceType: 'core',
      deliverables: [
        'Primary logo + variations (horizontal, stacked, icon-only)',
        'Color palette (primary, secondary, accent) with HEX/RGB/CMYK values',
        'Typography system (heading + body fonts, usage rules)',
        'Brand guidelines document (PDF, 15-30 pages)',
        'Asset library (social templates, email signature, favicon)',
        'File package (AI, SVG, PNG, EPS formats)',
      ],
      clientResponsibilities: [
        'Provide brand vision, values, and target audience overview',
        'Designate one decision-maker for feedback and approvals',
        'Provide timely feedback within 5 business days per review round',
        'Share examples of brands you admire for creative direction',
      ],
      outOfScope: [
        'Copywriting or tagline development',
        'Website design or development',
        'Brand photography or video production',
        'Trademark registration',
      ],
      defaultTimeline: '4-6 weeks. Discovery (Week 1), Concept Development (Weeks 2-3), Refinement (Week 4), Final Delivery (Weeks 5-6). Includes 2 rounds of revisions.',
      suggestedKpis: [
        'Brand recognition lift (pre/post survey)',
        'Brand consistency score across channels',
        'Internal adoption rate of new guidelines',
      ],
      commonTools: ['Adobe Illustrator', 'Figma', 'Canva (templates)', 'Brandfolder'],
    },
    {
      name: 'Brand Messaging & Voice',
      shortDesc: 'Brand positioning, messaging framework, and tone of voice',
      description: 'Define the verbal identity of the brand including positioning statement, value propositions, key messages for each audience segment, and a tone of voice guide. Ensures every piece of communication sounds like the same brand.',
      pricingModel: 'fixed',
      price: 4500,
      serviceType: 'core',
      deliverables: [
        'Brand positioning statement',
        'Core value propositions (3-5)',
        'Key messages per audience segment',
        'Tone of voice guide with do/don\'t examples',
        'Elevator pitch (15-sec, 30-sec, 60-sec versions)',
        'Boilerplate copy (company description, team bios template)',
      ],
      clientResponsibilities: [
        'Participate in brand workshop or stakeholder interviews',
        'Share existing marketing materials and messaging',
        'Identify key audience segments',
        'Provide feedback within agreed review windows',
      ],
      outOfScope: [
        'Visual identity or design work',
        'Ongoing content creation',
        'Website copywriting',
      ],
      defaultTimeline: '2-4 weeks. Stakeholder interviews (Week 1), Draft messaging framework (Week 2), Refinement and finalization (Weeks 3-4). Includes 2 rounds of revisions.',
      suggestedKpis: [
        'Message consistency across channels',
        'Team adoption of messaging framework',
        'Customer message recall in surveys',
      ],
      commonTools: ['Google Docs', 'Miro', 'Notion'],
    },
    {
      name: 'Graphic Design Retainer',
      shortDesc: 'Ongoing design support for marketing materials',
      description: 'Ongoing design support for day-to-day creative needs such as social graphics, presentation decks, event materials, print collateral, and ad creatives. Ideal for clients who need consistent design output without hiring in-house.',
      pricingModel: 'monthly',
      price: 2500,
      serviceType: 'addon',
      deliverables: [
        'Agreed number of design assets per month (defined in scope)',
        'Social media graphics and templates',
        'Presentation decks and pitch materials',
        'Print collateral (business cards, flyers, brochures)',
        'Event graphics (banners, signage, swag designs)',
        'Source files delivered in required formats',
      ],
      clientResponsibilities: [
        'Submit design briefs with clear requirements and copy',
        'Provide brand guidelines and asset library',
        'Give feedback within 2 business days per revision',
        'Manage print production and vendor relationships',
      ],
      outOfScope: [
        'Copywriting or content creation',
        'Brand identity changes or logo redesigns',
        'Video production or motion graphics',
      ],
      defaultTimeline: 'Ongoing monthly engagement. Initial setup: 1 week. Typical turnaround per request: 2-5 business days depending on complexity. Includes 1 round of revisions per piece.',
      suggestedKpis: [
        'Turnaround time per request',
        'Revision rate (lower = better briefs)',
        'Client satisfaction score',
      ],
      commonTools: ['Adobe Creative Suite', 'Figma', 'Canva', 'Asana/Monday for requests'],
    },
  ],

  'Website & Digital': [
    {
      name: 'Website Design & Development',
      shortDesc: 'Custom website design, development, and launch',
      description: 'Full website design and development from strategy through launch, including UX research, visual design, responsive development, CMS integration, and performance optimization. Focused on conversion and aligned with the client\'s brand and business goals.',
      pricingModel: 'fixed',
      price: 15000,
      serviceType: 'core',
      deliverables: [
        'Sitemap and information architecture',
        'Wireframes for key page templates',
        'Visual design mockups (desktop + mobile)',
        'Responsive development on agreed CMS platform',
        'CMS setup and content entry',
        'Basic SEO setup (meta titles, descriptions, schema)',
        'Performance optimization (Core Web Vitals)',
        'Launch checklist completion and go-live support',
      ],
      clientResponsibilities: [
        'Provide all page copy and imagery',
        'Provide brand guidelines and logo files',
        'Designate one decision-maker for design approvals',
        'Provide feedback within 5 business days per review round',
        'Manage domain registration and DNS settings',
        'Provide hosting credentials or approve recommended hosting',
      ],
      outOfScope: [
        'Copywriting (available as separate service)',
        'Professional photography or video production',
        'E-commerce functionality',
        'Ongoing maintenance after launch',
        'Third-party software licensing costs',
      ],
      defaultTimeline: '6-12 weeks. Discovery & Strategy (Weeks 1-2), Wireframes & UX (Weeks 3-4), Visual Design (Weeks 5-6), Development (Weeks 7-10), Testing & Launch (Weeks 11-12). Includes 2 rounds of design revisions.',
      suggestedKpis: [
        'Page load speed (under 3 seconds)',
        'Core Web Vitals scores (all green)',
        'Bounce rate reduction vs. previous site',
        'Conversion rate (form fills, CTAs)',
        'Mobile usability score',
      ],
      commonTools: ['Figma', 'Webflow / WordPress / Squarespace', 'Google Analytics', 'Google Search Console', 'GTmetrix'],
    },
    {
      name: 'Landing Page Design & Development',
      shortDesc: 'High-converting landing pages for campaigns',
      description: 'Conversion-focused landing page designed for a specific campaign, product launch, or lead generation goal. Includes A/B testing setup and integration with the client\'s CRM or email platform.',
      pricingModel: 'fixed',
      price: 3500,
      serviceType: 'core',
      deliverables: [
        'Landing page wireframe and copy structure',
        'Visual design mockup (desktop + mobile)',
        'Responsive development and deployment',
        'Form integration with CRM/email tool',
        'A/B test setup (headline, CTA, or layout variant)',
        'Tracking setup (conversion pixel, UTM parameters)',
        'Thank-you page or confirmation flow',
      ],
      clientResponsibilities: [
        'Provide campaign goals and target audience',
        'Provide or approve final landing page copy',
        'Provide product/service images and assets',
        'Provide CRM/email platform access for integration',
        'Manage ad traffic driving to the page',
      ],
      outOfScope: [
        'Copywriting (unless bundled)',
        'Paid ad campaign management',
        'Ongoing optimization beyond initial A/B test',
        'Full website design',
        'Video production for landing page',
      ],
      defaultTimeline: '2-3 weeks. Strategy & wireframe (Week 1), Design & development (Week 2), Testing & launch (Week 3). Includes 1 round of design revisions.',
      suggestedKpis: [
        'Conversion rate',
        'Cost per lead/acquisition',
        'Bounce rate',
        'A/B test winner confidence level',
      ],
      commonTools: ['Figma', 'Unbounce / Webflow / Instapage', 'Google Analytics', 'Hotjar'],
    },
    {
      name: 'Website Maintenance & Support',
      shortDesc: 'Ongoing updates, security, and hosting management',
      description: 'Ongoing website care including security updates, plugin management, content updates, performance monitoring, and technical support. Keeps the client\'s site secure, fast, and up to date without needing an in-house developer.',
      pricingModel: 'monthly',
      price: 800,
      serviceType: 'addon',
      deliverables: [
        'Monthly CMS, plugin, and theme updates',
        'Daily/weekly backups and recovery testing',
        'Uptime and performance monitoring',
        'Security scanning and malware removal',
        'Minor content updates (text, images, new pages)',
        'Monthly performance report',
        'Agreed development hours for enhancements',
      ],
      clientResponsibilities: [
        'Provide CMS and hosting credentials',
        'Submit change requests through agreed channel',
        'Approve significant changes before deployment',
        'Maintain hosting account and domain renewal',
      ],
      outOfScope: [
        'Major redesigns or new section development',
        'Content creation or copywriting',
        'SEO strategy',
        'Server infrastructure management (if self-hosted)',
        'Third-party platform troubleshooting',
      ],
      defaultTimeline: 'Ongoing monthly engagement. Onboarding: 1 week. Request turnaround: 1-3 business days for minor updates, 5-10 business days for development tasks.',
      suggestedKpis: [
        'Uptime percentage (target: 99.9%)',
        'Average response time to requests',
        'Number of security incidents',
        'Page speed scores maintained',
      ],
      commonTools: ['ManageWP / MainWP', 'Sucuri / Wordfence', 'Pingdom / UptimeRobot', 'WP Engine / Kinsta'],
    },
  ],

  'Content & Copywriting': [
    {
      name: 'Content Strategy & Planning',
      shortDesc: 'Audience research, content pillars, and editorial calendar',
      description: 'Develop a comprehensive content strategy including audience analysis, content pillars, editorial calendar, and distribution plan. Provides the strategic foundation for all content marketing efforts across blog, social, email, and other channels.',
      pricingModel: 'fixed',
      price: 5000,
      serviceType: 'core',
      deliverables: [
        'Content audit of existing materials',
        'Audience persona alignment and content mapping',
        'Content pillar framework (3-5 core topics)',
        'Editorial calendar (3-6 months)',
        'Content brief templates for each content type',
        'Distribution and promotion playbook',
        'SEO keyword integration strategy',
        'KPI dashboard setup and measurement framework',
      ],
      clientResponsibilities: [
        'Share business goals, target audience, and competitive landscape',
        'Provide access to existing content assets and analytics',
        'Designate a content point of contact',
        'Participate in strategy workshop (2-3 hours)',
        'Approve editorial calendar and content briefs',
      ],
      outOfScope: [
        'Content creation or writing',
        'Graphic design for content',
        'Video production',
        'Paid media strategy',
        'Social media community management',
      ],
      defaultTimeline: '3-4 weeks. Audit & research (Week 1), Strategy development (Week 2), Calendar & playbook (Week 3), Finalization (Week 4). Includes 2 rounds of revisions.',
      suggestedKpis: [
        'Content production cadence adherence',
        'Organic traffic growth',
        'Engagement rate by content type',
        'Lead generation from content',
      ],
      commonTools: ['SEMrush / Ahrefs', 'Google Analytics', 'Notion / Asana', 'Google Search Console'],
    },
    {
      name: 'Blog & Article Writing',
      shortDesc: 'SEO-optimized blog posts with keyword research',
      description: 'Professional blog and article writing optimized for SEO and audience engagement. Each piece is researched, written, optimized, and formatted for publishing. Can be one-off or ongoing monthly content production.',
      pricingModel: 'monthly',
      price: 2000,
      serviceType: 'core',
      deliverables: [
        'SEO-optimized blog posts/articles at agreed word count',
        'Keyword research and targeting per piece',
        'Meta title and meta description',
        'Internal linking suggestions',
        'Featured image recommendations or specifications',
        'CMS formatting and publishing (if access provided)',
      ],
      clientResponsibilities: [
        'Approve content briefs and topics',
        'Provide subject matter expertise or access to SMEs for interviews',
        'Review and approve drafts within 3 business days',
        'Provide CMS access for publishing (if agency publishes)',
        'Share brand voice guidelines',
      ],
      outOfScope: [
        'Graphic design or custom illustrations',
        'Video or multimedia content creation',
        'Content promotion or social distribution',
        'Technical SEO implementation',
        'Translation or localization',
      ],
      defaultTimeline: 'Per piece: 5-7 business days from brief approval to final draft. Monthly packages: rolling delivery per editorial calendar. Includes 1 round of revisions per article.',
      suggestedKpis: [
        'Organic traffic per article (after 90 days)',
        'Average time on page',
        'Keyword ranking positions',
        'Leads/conversions attributed to content',
      ],
      commonTools: ['SEMrush / Ahrefs', 'Clearscope / SurferSEO', 'Google Docs', 'WordPress / CMS'],
    },
    {
      name: 'Website Copywriting',
      shortDesc: 'Conversion-focused copy for all website pages',
      description: 'Conversion-focused copy for website pages including homepage, about, services, and key landing pages. Written to align with brand voice, communicate value propositions clearly, and drive visitor action.',
      pricingModel: 'fixed',
      price: 3500,
      serviceType: 'core',
      deliverables: [
        'Copy for each agreed page (headline, subheads, body, CTAs)',
        'SEO-optimized meta titles and descriptions per page',
        'CTA copy and microcopy (buttons, forms, error states)',
        'Copy deck organized by page and section',
        'Copy notes explaining strategic reasoning',
      ],
      clientResponsibilities: [
        'Provide brand messaging framework (or engage Messaging module)',
        'Share target audience and unique selling propositions',
        'Provide wireframes or page structures for copy placement',
        'Designate one approver for copy sign-off',
        'Provide feedback within 5 business days',
      ],
      outOfScope: [
        'Blog writing or ongoing content',
        'UX/UI design or wireframing',
        'Website development',
        'Legal page copy (privacy policy, terms of service)',
        'Product descriptions for e-commerce',
      ],
      defaultTimeline: '2-4 weeks. Research & sitemap review (Week 1), First draft (Week 2), Revisions (Week 3), Final delivery (Week 4). Includes 2 rounds of revisions.',
      suggestedKpis: [
        'Conversion rate improvement',
        'Bounce rate reduction',
        'Time on page increase',
        'SEO ranking for target keywords',
      ],
      commonTools: ['Google Docs', 'Hemingway Editor', 'SEMrush'],
    },
    {
      name: 'Email Copywriting',
      shortDesc: 'Email sequences, campaigns, and newsletter content',
      description: 'Copywriting for email campaigns including welcome sequences, nurture flows, newsletters, and promotional emails. Focused on open rates, click-through rates, and driving conversions through the inbox.',
      pricingModel: 'fixed',
      price: 1500,
      serviceType: 'addon',
      deliverables: [
        'Email copy (subject line, preview text, body, CTA)',
        'A/B test subject line variants',
        'Segmentation recommendations',
        'Email sequence flow and timing logic',
        'Performance benchmark targets',
      ],
      clientResponsibilities: [
        'Provide email platform access or agree to copy delivery format',
        'Share subscriber list details and segmentation',
        'Provide offers, promotions, or content to feature',
        'Approve email copy before scheduling',
        'Manage email list and compliance (GDPR, CAN-SPAM)',
      ],
      outOfScope: [
        'Email template design',
        'Email platform setup or migration',
        'List building or lead generation',
        'Marketing automation setup',
        'Deliverability optimization',
      ],
      defaultTimeline: 'Per email: 3-5 business days. Sequences: 2-3 weeks. Includes 1 round of revisions per email.',
      suggestedKpis: [
        'Open rate',
        'Click-through rate',
        'Conversion rate',
        'Unsubscribe rate',
      ],
      commonTools: ['Mailchimp / Klaviyo / ActiveCampaign', 'Google Docs'],
    },
  ],

  'SEO & Organic Growth': [
    {
      name: 'SEO Strategy & Implementation',
      shortDesc: 'Technical SEO, on-page optimization, and link building',
      description: 'Comprehensive search engine optimization including technical audit, on-page optimization, keyword strategy, and ongoing implementation. Designed to increase organic visibility, drive qualified traffic, and build long-term search authority.',
      pricingModel: 'monthly',
      price: 3500,
      serviceType: 'core',
      deliverables: [
        'Technical SEO audit with prioritized fixes',
        'Keyword research and mapping to pages',
        'On-page optimization (titles, metas, headers, internal links)',
        'Content gap analysis and recommendations',
        'Monthly ranking and traffic reports',
        'Competitor SEO benchmarking',
        'Schema markup implementation',
        'Google Business Profile optimization (if local)',
      ],
      clientResponsibilities: [
        'Provide Google Analytics and Search Console access',
        'Provide CMS access for on-page changes',
        'Implement technical fixes or provide developer access',
        'Approve content recommendations before production',
        'Share business priorities and seasonal patterns',
      ],
      outOfScope: [
        'Content writing',
        'Link building outreach',
        'Paid search/PPC',
        'Website design or major development changes',
        'Social media optimization',
      ],
      defaultTimeline: 'Audit: 2-3 weeks. Ongoing: minimum 6-month engagement for meaningful results. Monthly implementation cycles with quarterly strategy reviews.',
      suggestedKpis: [
        'Organic traffic growth (month-over-month)',
        'Keyword ranking positions (top 10, top 3)',
        'Organic conversion rate',
        'Domain authority growth',
        'Core Web Vitals scores',
      ],
      commonTools: ['SEMrush / Ahrefs / Moz', 'Google Search Console', 'Google Analytics', 'Screaming Frog', 'Schema.org'],
    },
    {
      name: 'Local SEO',
      shortDesc: 'Google Business Profile, local citations, and review management',
      description: 'Optimize the client\'s presence for local search including Google Business Profile management, local citation building, review management strategy, and location-specific content optimization.',
      pricingModel: 'monthly',
      price: 1000,
      serviceType: 'addon',
      deliverables: [
        'Google Business Profile audit and optimization',
        'Local citation audit and cleanup',
        'NAP (Name, Address, Phone) consistency check',
        'Review generation strategy and response templates',
        'Local keyword research and on-page optimization',
        'Monthly local ranking reports',
      ],
      clientResponsibilities: [
        'Provide Google Business Profile access',
        'Verify business information accuracy',
        'Respond to customer reviews (or approve agency responses)',
        'Provide photos of business, team, and products/services',
      ],
      outOfScope: [
        'Reputation management beyond review strategy',
        'Physical signage or print advertising',
        'Multi-location enterprise SEO',
        'Paid local ads (Google Local Services)',
        'Website development',
      ],
      defaultTimeline: 'Setup: 2 weeks. Ongoing monthly management. Results visible within 2-4 months.',
      suggestedKpis: [
        'Google Business Profile views and actions',
        'Local pack ranking positions',
        'Review count and average rating',
        'Local organic traffic',
      ],
      commonTools: ['Google Business Profile', 'BrightLocal / Whitespark', 'Moz Local'],
    },
  ],

  'Social Media': [
    {
      name: 'Social Media Management',
      shortDesc: 'Content creation, scheduling, and community management',
      description: 'End-to-end social media management including strategy, content creation, scheduling, publishing, community management, and performance reporting. Covers the client\'s primary social platforms to build audience, engagement, and brand presence.',
      pricingModel: 'monthly',
      price: 3000,
      serviceType: 'core',
      deliverables: [
        'Social media strategy and platform recommendations',
        'Monthly content calendar with post copy and visuals',
        'Content creation (graphics, captions, hashtags)',
        'Scheduling and publishing on agreed platforms',
        'Daily community management (responses within 4 hours)',
        'Monthly analytics report with insights and recommendations',
        'Quarterly strategy review and optimization',
      ],
      clientResponsibilities: [
        'Provide social platform login credentials',
        'Approve monthly content calendar before publishing',
        'Share company news, events, and promotions for content',
        'Provide product/service photos and behind-the-scenes content',
        'Flag any sensitive topics or customer issues for response',
        'Respond to DMs requiring business-specific expertise',
      ],
      outOfScope: [
        'Paid social advertising',
        'Influencer marketing and partnerships',
        'Video production (short-form video add-on available)',
        'Crisis communications management',
        'Personal social media accounts for executives',
        'Social media platform ad account setup fees',
      ],
      defaultTimeline: 'Onboarding: 1-2 weeks (strategy + first month calendar). Ongoing monthly with content delivered 1 week in advance for approval. Minimum 3-month commitment recommended.',
      suggestedKpis: [
        'Follower growth rate',
        'Engagement rate per post',
        'Reach and impressions',
        'Website traffic from social',
        'Response time to comments/messages',
      ],
      commonTools: ['Hootsuite / Buffer / Sprout Social', 'Canva / Adobe Express', 'Later', 'Meta Business Suite'],
    },
    {
      name: 'Short-Form Video Content',
      shortDesc: 'Reels, TikToks, and YouTube Shorts production',
      description: 'Creation of short-form video content for Instagram Reels, TikTok, YouTube Shorts, and LinkedIn. Includes concept development, scripting, filming guidance or editing of client footage, and optimized publishing.',
      pricingModel: 'monthly',
      price: 2500,
      serviceType: 'addon',
      deliverables: [
        'Video concepts and scripts/outlines',
        'Edited short-form videos (15-60 seconds)',
        'Captions and subtitles',
        'Platform-optimized formatting (vertical, square)',
        'Trending audio and hashtag recommendations',
        'Publishing and scheduling',
      ],
      clientResponsibilities: [
        'Film raw footage per agency guidance (or arrange filming)',
        'Provide product/service access for content creation',
        'Approve concepts and final edits before publishing',
        'Participate in on-camera content if required',
      ],
      outOfScope: [
        'Professional videography or on-site filming',
        'Long-form video production (over 2 minutes)',
        'Paid promotion of videos',
        'YouTube channel management',
        'Podcast production',
      ],
      defaultTimeline: 'Per video: 3-5 business days from footage receipt. Monthly packages: rolling delivery per content calendar.',
      suggestedKpis: [
        'Video views and watch-through rate',
        'Engagement (likes, comments, shares, saves)',
        'Follower growth from video content',
        'Trending/viral hit rate',
      ],
      commonTools: ['CapCut / Adobe Premiere Rush', 'Canva', 'InShot', 'TikTok / Instagram'],
    },
  ],

  'Paid Advertising': [
    {
      name: 'Paid Search (PPC) Management',
      shortDesc: 'Google Ads management with keyword strategy',
      description: 'Google Ads and Microsoft Ads campaign management including strategy, setup, creative, bid management, and ongoing optimization. Focused on maximizing return on ad spend through data-driven campaign management.',
      pricingModel: 'monthly',
      price: 3000,
      serviceType: 'core',
      deliverables: [
        'Campaign strategy and account structure',
        'Keyword research and match type strategy',
        'Ad copy creation (responsive search ads, extensions)',
        'Landing page recommendations',
        'Bid strategy setup and optimization',
        'Negative keyword management',
        'Conversion tracking setup',
        'Weekly optimization and bid adjustments',
        'Monthly performance report with insights',
      ],
      clientResponsibilities: [
        'Provide Google Ads account access (or allow agency to create)',
        'Fund ad spend directly (separate from management fee)',
        'Approve ad copy and landing pages',
        'Provide product/service information for campaign targeting',
        'Share conversion data and sales feedback',
        'Respond to lead inquiries generated by campaigns',
      ],
      outOfScope: [
        'Ad spend budget (billed directly by platform)',
        'Landing page design and development',
        'Organic SEO',
        'Social media advertising',
        'CRM setup or sales process optimization',
      ],
      defaultTimeline: 'Setup: 1-2 weeks. Optimization: ongoing monthly. Minimum 3-month commitment for meaningful data and results. Expect 60-90 days for full optimization.',
      suggestedKpis: [
        'Return on Ad Spend (ROAS)',
        'Cost per conversion/lead',
        'Click-through rate (CTR)',
        'Quality Score improvements',
        'Impression share',
      ],
      commonTools: ['Google Ads', 'Microsoft Ads', 'Google Analytics', 'Google Tag Manager', 'SEMrush'],
    },
    {
      name: 'Paid Social Advertising',
      shortDesc: 'Meta, LinkedIn, and TikTok ad campaigns',
      description: 'Social media advertising across Meta (Facebook & Instagram), LinkedIn, TikTok, and other platforms. Includes campaign strategy, audience targeting, creative development, and ongoing optimization to drive leads, sales, or awareness.',
      pricingModel: 'monthly',
      price: 3000,
      serviceType: 'core',
      deliverables: [
        'Campaign strategy and targeting plan',
        'Audience research and segmentation (custom, lookalike, interest)',
        'Ad creative (static images, carousels, video edits)',
        'Ad copy variations for testing',
        'Pixel/tracking setup and event configuration',
        'A/B testing framework',
        'Weekly optimization and budget allocation',
        'Monthly performance report with creative insights',
      ],
      clientResponsibilities: [
        'Provide ad platform access and Business Manager admin',
        'Fund ad spend directly',
        'Provide or approve product/service imagery and video',
        'Approve ad copy and creative before launch',
        'Share audience insights and customer data for targeting',
        'Respond to leads and inquiries from campaigns',
      ],
      outOfScope: [
        'Ad spend budget',
        'Professional photography or video production',
        'Organic social media management',
        'Landing page creation',
        'Influencer partnerships',
        'CRM or marketing automation integration',
      ],
      defaultTimeline: 'Setup: 1-2 weeks. Optimization: ongoing monthly. Minimum 3-month commitment. Learning phase: 2-4 weeks per campaign.',
      suggestedKpis: [
        'Cost per acquisition (CPA)',
        'Return on Ad Spend (ROAS)',
        'Click-through rate (CTR)',
        'Cost per thousand impressions (CPM)',
        'Conversion rate by audience segment',
      ],
      commonTools: ['Meta Ads Manager', 'LinkedIn Campaign Manager', 'TikTok Ads', 'Google Analytics', 'Triple Whale / Hyros'],
    },
  ],

  'Email Marketing': [
    {
      name: 'Email Marketing Management',
      shortDesc: 'Full email strategy with campaigns and automation',
      description: 'Full email marketing management including strategy, campaign planning, template design, copy, automation flows, list management, and performance optimization. Drives engagement, nurtures leads, and increases customer lifetime value.',
      pricingModel: 'monthly',
      price: 2000,
      serviceType: 'core',
      deliverables: [
        'Email marketing strategy and calendar',
        'Campaign design and copywriting',
        'Email template creation (branded, responsive)',
        'Automation flow setup (welcome, abandoned cart, re-engagement)',
        'List segmentation and management',
        'A/B testing (subject lines, content, send times)',
        'Monthly analytics report',
        'Deliverability monitoring and optimization',
      ],
      clientResponsibilities: [
        'Provide email platform access',
        'Share subscriber lists and consent documentation',
        'Provide promotional offers and company news',
        'Approve email campaigns before sending',
        'Maintain compliance with email regulations',
        'Share product imagery and brand assets',
      ],
      outOfScope: [
        'Email platform subscription costs',
        'List building or lead generation',
        'Transactional email development (order confirmations, etc.)',
        'SMS/text message marketing',
        'Custom email platform development or migration',
        'Direct mail campaigns',
      ],
      defaultTimeline: 'Setup and onboarding: 2-3 weeks. First campaign: Week 3-4. Ongoing monthly management. Minimum 3-month commitment recommended.',
      suggestedKpis: [
        'Open rate',
        'Click-through rate',
        'Conversion rate',
        'Revenue per email',
        'List growth rate',
        'Unsubscribe rate',
      ],
      commonTools: ['Mailchimp / Klaviyo / ActiveCampaign / HubSpot', 'Litmus', 'Google Analytics'],
    },
  ],

  'Marketing Automation & CRM': [
    {
      name: 'Marketing Automation Setup',
      shortDesc: 'Lead scoring, nurture sequences, and CRM integration',
      description: 'Setup and configuration of marketing automation workflows including lead scoring, nurture sequences, behavioral triggers, and CRM integration. Turns manual marketing processes into scalable, automated systems.',
      pricingModel: 'fixed',
      price: 5000,
      serviceType: 'core',
      deliverables: [
        'Automation platform audit or setup',
        'Workflow mapping and documentation',
        'Lead scoring model configuration',
        'Nurture sequence builds (email + triggers)',
        'CRM integration and field mapping',
        'Form and landing page integration',
        'Reporting dashboard setup',
        'Team training documentation',
      ],
      clientResponsibilities: [
        'Provide platform credentials and admin access',
        'Define lead qualification criteria with sales team',
        'Provide email copy and content for sequences (or engage copywriting module)',
        'Participate in workflow planning sessions',
        'Ensure sales team adoption and feedback loop',
      ],
      outOfScope: [
        'Platform subscription fees',
        'Email copywriting',
        'CRM customization beyond marketing integrations',
        'Sales process consulting',
        'Custom API development',
        'Data migration from legacy systems',
      ],
      defaultTimeline: '4-8 weeks. Audit & planning (Weeks 1-2), Build & configure (Weeks 3-6), Testing & launch (Weeks 7-8). Includes user acceptance testing.',
      suggestedKpis: [
        'Marketing Qualified Leads (MQLs) generated',
        'Lead-to-customer conversion rate',
        'Automation engagement rates',
        'Time saved on manual processes',
        'Sales cycle length reduction',
      ],
      commonTools: ['HubSpot / ActiveCampaign / Marketo / Pardot', 'Zapier / Make', 'Salesforce / Pipedrive'],
    },
  ],

  'Analytics & Reporting': [
    {
      name: 'Analytics & Reporting Setup',
      shortDesc: 'GA4, Tag Manager, and conversion tracking implementation',
      description: 'Setup and configuration of marketing analytics including tracking implementation, dashboard creation, attribution modeling, and reporting frameworks. Gives the client clear visibility into what\'s working and what\'s not across all marketing channels.',
      pricingModel: 'fixed',
      price: 3000,
      serviceType: 'core',
      deliverables: [
        'Google Analytics 4 setup and configuration',
        'Conversion tracking and goal setup',
        'Google Tag Manager implementation',
        'Custom dashboard(s) in Looker Studio or equivalent',
        'UTM tagging framework and documentation',
        'Monthly/weekly performance report',
        'Attribution model recommendation and setup',
        'Data quality audit and cleanup',
      ],
      clientResponsibilities: [
        'Provide website and platform access for tag installation',
        'Provide Google Analytics and Tag Manager access',
        'Define key business metrics and goals',
        'Ensure developer availability for tracking implementation',
        'Review and act on reporting insights',
      ],
      outOfScope: [
        'Data warehousing or BI tool development',
        'CRM analytics or sales reporting',
        'A/B testing tool setup',
        'Custom data science or machine learning',
        'Platform-specific ad reporting (covered in ad modules)',
      ],
      defaultTimeline: 'Setup: 2-4 weeks. Dashboards: delivered with setup. Ongoing reporting: monthly or weekly cadence.',
      suggestedKpis: [
        'Data accuracy and completeness',
        'Reporting delivery timeliness',
        'Actionable insights per report cycle',
      ],
      commonTools: ['Google Analytics 4', 'Google Tag Manager', 'Looker Studio', 'Mixpanel / Amplitude', 'Hotjar'],
    },
  ],

  'Strategy & Consulting': [
    {
      name: 'Marketing Strategy & Consulting',
      shortDesc: 'Strategic planning, market analysis, and growth roadmap',
      description: 'High-level marketing strategy development including market analysis, competitive positioning, channel strategy, budget allocation, and go-to-market planning. Ideal for clients who need strategic direction before tactical execution.',
      pricingModel: 'fixed',
      price: 5000,
      serviceType: 'core',
      deliverables: [
        'Market and competitive analysis',
        'Customer/audience segmentation',
        'Channel strategy and prioritization',
        'Budget allocation recommendations',
        '90-day action plan with milestones',
        'KPI framework and measurement plan',
        'Monthly strategy review sessions (if ongoing)',
      ],
      clientResponsibilities: [
        'Share business goals, revenue targets, and constraints',
        'Provide access to existing marketing data and spend',
        'Participate actively in strategy sessions',
        'Designate decision-maker with authority to approve strategy',
        'Commit resources to execute on strategy recommendations',
      ],
      outOfScope: [
        'Tactical execution of strategy',
        'Sales strategy or process optimization',
        'Product development strategy',
        'Organizational restructuring',
        'Market research beyond desk research',
      ],
      defaultTimeline: 'Strategy project: 3-5 weeks. Advisory: ongoing monthly with quarterly deep-dives.',
      suggestedKpis: [
        'Strategy adoption rate by team',
        'Marketing ROI improvement',
        'Channel performance vs. benchmarks',
        'Goal attainment rate',
      ],
      commonTools: ['Google Analytics', 'SEMrush / SimilarWeb', 'Miro / FigJam', 'Google Slides / Notion'],
    },
  ],

  'Conversion Rate Optimization': [
    {
      name: 'CRO & A/B Testing',
      shortDesc: 'A/B testing, user research, and funnel optimization',
      description: 'Data-driven conversion rate optimization including user behavior analysis, hypothesis development, A/B test design and execution, and implementation of winning variations. Turns existing traffic into more leads and customers.',
      pricingModel: 'monthly',
      price: 2500,
      serviceType: 'addon',
      deliverables: [
        'Conversion audit and opportunity analysis',
        'User behavior analysis (heatmaps, recordings, funnels)',
        'Test hypothesis backlog (prioritized)',
        'A/B test design and implementation',
        'Statistical analysis and winner declaration',
        'Implementation of winning variations',
        'Monthly CRO report with learnings',
      ],
      clientResponsibilities: [
        'Provide website and analytics access',
        'Provide developer resources for test implementation (if needed)',
        'Approve test hypotheses before launch',
        'Maintain sufficient traffic for statistical significance',
        'Implement winning variations permanently',
      ],
      outOfScope: [
        'Website redesign',
        'Traffic generation or paid ads',
        'UX research beyond CRO scope',
        'Backend or server-side testing',
        'Mobile app optimization',
      ],
      defaultTimeline: 'Audit: 1-2 weeks. Testing cycles: 2-4 weeks per test depending on traffic. Minimum 3-month engagement for meaningful impact.',
      suggestedKpis: [
        'Conversion rate improvement (overall and per test)',
        'Revenue impact of winning tests',
        'Test velocity (tests launched per month)',
        'Win rate (percentage of tests with positive results)',
      ],
      commonTools: ['Google Optimize / VWO / Optimizely', 'Hotjar / FullStory', 'Google Analytics'],
    },
  ],

  'PR & Communications': [
    {
      name: 'PR & Media Relations',
      shortDesc: 'Media outreach, press releases, and earned media',
      description: 'Public relations support including media outreach, press release writing, journalist relationship management, and earned media placement. Builds credibility and awareness through trusted third-party coverage.',
      pricingModel: 'monthly',
      price: 3000,
      serviceType: 'addon',
      deliverables: [
        'Media list development (targeted journalists and outlets)',
        'Press releases and media pitches',
        'Media outreach and follow-up',
        'Media monitoring and coverage tracking',
        'Monthly coverage report',
        'Spokesperson preparation and talking points',
        'Crisis communication framework (if ongoing)',
      ],
      clientResponsibilities: [
        'Provide newsworthy stories, launches, and milestones',
        'Designate spokesperson(s) available for media requests',
        'Approve press releases and talking points before outreach',
        'Respond to media interview requests promptly',
        'Share company news and developments proactively',
      ],
      outOfScope: [
        'Paid media or sponsored content',
        'Social media management',
        'Event planning and logistics',
        'Investor relations',
        'Government relations or lobbying',
      ],
      defaultTimeline: 'Onboarding: 1-2 weeks. First outreach: Week 3. Ongoing monthly with media placements typically within 4-8 weeks. Minimum 3-month commitment.',
      suggestedKpis: [
        'Media placements and coverage volume',
        'Share of voice vs. competitors',
        'Media quality tier (Tier 1, 2, 3)',
        'Website traffic from earned media',
        'Domain authority impact from backlinks',
      ],
      commonTools: ['Muck Rack / Cision / HARO', 'Meltwater / Mention', 'Google Alerts'],
    },
  ],
};

export function getDefaultModulesForGroup(groupName: string): DefaultModule[] {
  return defaultModulesByGroup[groupName] || [];
}
